# Site settings
title:          Taisa Grant
description:    "A Technical Documentation Blog"
baseurl:        "/"
url:            "http://taisagrant.com"

# Author
author:
  name:         Taisa
  url:          https://taisagrant.com
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
